TableSkill = TableSkill or { 
[1001] = { ["Target_type"] = 0, ["Attack_Types"] = 0, ["Attack_Distance"] = 10, ["Att_Range"] = 30, ["Angle"] = 30, ["Attack_Coefficient"] = 1000, ["Grade_Coefficient"] = 0, ["Skill_Name"] = "普通攻击1", ["ActionName"] = "Attack1", ["Open_Class"] = 1, ["Ability_Describe"] = "正切"},
[1002] = { ["Target_type"] = 0, ["Attack_Types"] = 0, ["Attack_Distance"] = 10, ["Att_Range"] = 30, ["Angle"] = 30, ["Attack_Coefficient"] = 1000, ["Grade_Coefficient"] = 0, ["Skill_Name"] = "普通攻击2", ["ActionName"] = "Attack2", ["Open_Class"] = 1, ["Ability_Describe"] = "反切"},
[1003] = { ["Target_type"] = 0, ["Attack_Types"] = 0, ["Attack_Distance"] = 10, ["Att_Range"] = 30, ["Angle"] = 30, ["Attack_Coefficient"] = 1000, ["Grade_Coefficient"] = 0, ["Skill_Name"] = "普通攻击3", ["ActionName"] = "Attack3", ["Open_Class"] = 1, ["Ability_Describe"] = "劈"},
[1004] = { ["Target_type"] = 0, ["Attack_Types"] = 0, ["Attack_Distance"] = 10, ["Att_Range"] = 30, ["Angle"] = 30, ["Attack_Coefficient"] = 1500, ["Grade_Coefficient"] = 10, ["Skill_Name"] = "跳劈", ["ActionName"] = "Jump_Hack", ["Open_Class"] = 1, ["Ability_Describe"] = "跳跃后砸击地面，给予目标沉重打击，被击中的目标会减速"},
[1005] = { ["Target_type"] = 0, ["Attack_Types"] = 2, ["Attack_Distance"] = 30, ["Att_Range"] = 30, ["Angle"] = 30, ["Attack_Coefficient"] = 1500, ["Grade_Coefficient"] = 10, ["Skill_Name"] = "剑气", ["Open_Class"] = 1, ["Ability_Describe"] = "迅速往前方挥刀，攻击前方3格目标"},
[1006] = { ["Target_type"] = 0, ["Attack_Types"] = 1, ["Attack_Distance"] = 15, ["Att_Range"] = 30, ["Angle"] = 30, ["Attack_Coefficient"] = 1500, ["Grade_Coefficient"] = 10, ["Skill_Name"] = "旋风斩", ["ActionName"] = "Rotation", ["Open_Class"] = 4, ["Ability_Describe"] = "快速转动武器，自由转动对周围目标造成伤害"},
[1007] = { ["Target_type"] = 0, ["Attack_Types"] = 0, ["Attack_Distance"] = 10, ["Att_Range"] = 30, ["Angle"] = 30, ["Attack_Coefficient"] = 1500, ["Grade_Coefficient"] = 10, ["Skill_Name"] = "瞬杀", ["Open_Class"] = 7, ["Ability_Describe"] = "进入隐身状态持续一定时间，隐身中造成大量伤害，攻击后现身"},
[1008] = { ["Target_type"] = 0, ["Attack_Types"] = 0, ["Attack_Distance"] = 15, ["Att_Range"] = 30, ["Angle"] = 30, ["Attack_Coefficient"] = 1500, ["Grade_Coefficient"] = 10, ["Skill_Name"] = "无敌斩", ["Open_Class"] = 10, ["Ability_Describe"] = "对目标连续造成瞬间伤害，此时处于无敌状态"}
}