TableSkill = TableSkill or { 
[11] = { ["Target_type"] = 0, ["Attack_Types"] = 0, ["Attack_Distance"] = 10, ["Att_Range"] = 30, ["Angle"] = 30, ["Attack_Coefficient"] = 1000, ["Grade_Coefficient"] = 0, ["Skill_Name"] = "普通攻击1", ["ActionName"] = "Attack1", ["Open_Class"] = 1, ["Ability_Describe"] = "正切", ["Skill_CD"] = 375, ["Public_CD"] = 0, ["SkillType"] = 1},
[12] = { ["Target_type"] = 0, ["Attack_Types"] = 0, ["Attack_Distance"] = 10, ["Att_Range"] = 30, ["Angle"] = 30, ["Attack_Coefficient"] = 1000, ["Grade_Coefficient"] = 0, ["Skill_Name"] = "普通攻击2", ["ActionName"] = "Attack2", ["Open_Class"] = 1, ["Ability_Describe"] = "反切", ["Skill_CD"] = 834, ["Public_CD"] = 0, ["SkillType"] = 1},
[13] = { ["Target_type"] = 0, ["Attack_Types"] = 0, ["Attack_Distance"] = 10, ["Att_Range"] = 30, ["Angle"] = 30, ["Attack_Coefficient"] = 1000, ["Grade_Coefficient"] = 0, ["Skill_Name"] = "普通攻击3", ["ActionName"] = "Attack3", ["Open_Class"] = 1, ["Ability_Describe"] = "劈", ["Skill_CD"] = 792, ["Public_CD"] = 0, ["SkillType"] = 1},
[21] = { ["Target_type"] = 0, ["Attack_Types"] = 0, ["Attack_Distance"] = 10, ["Att_Range"] = 30, ["Angle"] = 30, ["Attack_Coefficient"] = 1000, ["Grade_Coefficient"] = 0, ["Skill_Name"] = "普通攻击1", ["ActionName"] = "Attack1", ["Ability_Describe"] = "枪普通攻击", ["Skill_CD"] = 1125, ["Public_CD"] = 0, ["SkillType"] = 2},
[1010] = { ["Target_type"] = 0, ["Attack_Types"] = 0, ["Attack_Distance"] = 10, ["Att_Range"] = 30, ["Angle"] = 30, ["Attack_Coefficient"] = 1500, ["Grade_Coefficient"] = 10, ["Skill_Name"] = "跳劈", ["Icon_Path"] = "tiaopi", ["ActionName"] = "Skill1", ["Open_Class"] = 1, ["Ability_Describe"] = "跳跃后砸击地面，给予目标沉重打击，被击中的目标会减速", ["Skill_CD"] = 1000, ["Public_CD"] = 300, ["SkillType"] = 1, ["Touch_Buff"] = 0, ["Check_Buff"] = 0},
[1020] = { ["Target_type"] = 0, ["Attack_Types"] = 2, ["Attack_Distance"] = 30, ["Att_Range"] = 30, ["Angle"] = 30, ["Attack_Coefficient"] = 1500, ["Grade_Coefficient"] = 10, ["Skill_Name"] = "剑气", ["Icon_Path"] = "jianqi", ["ActionName"] = "Skill2", ["Open_Class"] = 1, ["Ability_Describe"] = "迅速往前方挥刀，攻击前方3格目标", ["Skill_CD"] = 1000, ["Public_CD"] = 300, ["SkillType"] = 1, ["Touch_Buff"] = 0, ["Check_Buff"] = 0},
[1030] = { ["Target_type"] = 0, ["Attack_Types"] = 3, ["Attack_Distance"] = 15, ["Att_Range"] = 30, ["Angle"] = 30, ["Attack_Coefficient"] = 1500, ["Grade_Coefficient"] = 10, ["Skill_Name"] = "旋风斩", ["Icon_Path"] = "xuanfengzhan", ["ActionName"] = "Skill3", ["Open_Class"] = 4, ["Ability_Describe"] = "快速转动武器，自由转动对周围目标造成伤害", ["Skill_CD"] = 10000, ["Public_CD"] = 300, ["SkillType"] = 1, ["Touch_Buff"] = 3001, ["Check_Buff"] = 0},
[1040] = { ["Target_type"] = 0, ["Attack_Types"] = 0, ["Attack_Distance"] = 10, ["Att_Range"] = 30, ["Angle"] = 30, ["Attack_Coefficient"] = 1500, ["Grade_Coefficient"] = 10, ["Skill_Name"] = "瞬杀", ["Icon_Path"] = "shunsha", ["ActionName"] = "Skill4", ["Open_Class"] = 7, ["Ability_Describe"] = "进入隐身状态持续一定时间，隐身中造成大量伤害，攻击后现身", ["Skill_CD"] = 1000, ["Public_CD"] = 300, ["SkillType"] = 1, ["Touch_Buff"] = 0, ["Check_Buff"] = 0},
[1050] = { ["Target_type"] = 0, ["Attack_Types"] = 0, ["Attack_Distance"] = 15, ["Att_Range"] = 30, ["Angle"] = 30, ["Attack_Coefficient"] = 1500, ["Grade_Coefficient"] = 10, ["Skill_Name"] = "无敌斩", ["Icon_Path"] = "wudizhan", ["ActionName"] = "Skill5", ["Open_Class"] = 10, ["Ability_Describe"] = "对目标连续造成瞬间伤害，此时处于无敌状态", ["Skill_CD"] = 1000, ["Public_CD"] = 300, ["SkillType"] = 1, ["Touch_Buff"] = 0, ["Check_Buff"] = 0}
}